---
name: "⛔ Bug Report"
description: Report a bug
title: "short issue description"
labels: [bug]
assignees: []
body:
  - type: input
    id: Board
    attributes:
      label: Board type
      description: e.g. nrf9160 dk | thingy91 | STM32 P-L496G-CELL02
    validations:
      required: true
  - type: input
    id: Modem
    attributes:
      label: Modem
      description: e.g. BG96 | SARA-R4
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What is the problem? A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: |
        What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: |
        What actually happened? 
        Please include full errors, and relevant logs.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: |
        Provide a short, self-contained, Correct(Compilable), concise snippet of code that can be used to reproduce the issue.
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: Other information
      description: |
        e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, slack, etc
    validations:
      required: false
