name: CMake

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
     image: ghcr.io/1nce-gmbh/1nce-iot-c-sdk:latest
     credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.CONTAINER_KEY }}

    steps:
    - uses: actions/checkout@v2

    - name: Build (CMake)
      run: |
        cmake -S test -B build/  \
        -G "Unix Makefiles" \
        -DCMAKE_BUILD_TYPE=Debug \
        -DBUILD_CLONE_SUBMODULES=ON \
        -DCMAKE_C_FLAGS='--coverage -Wall -Wextra -Werror -DNDEBUG'
         make -C build/ all
         
  complexity:
    runs-on: ubuntu-latest
    container:
     image: ghcr.io/1nce-gmbh/1nce-iot-c-sdk:latest
     credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.CONTAINER_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: Check complexity
      run: find source/ -iname '*.c' |
           xargs complexity --scores --threshold=0 --horrid-threshold=8
       

  formatting:
    runs-on: ubuntu-latest
    container:
     image: ghcr.io/1nce-gmbh/1nce-iot-c-sdk:latest
     credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.CONTAINER_KEY }}

    steps:
    - uses: actions/checkout@v2             
    - name: Check formatting
      run: cd source && find . -iname "*.[hc]" -type f -exec uncrustify --check -c ../tools/uncrustify.cfg -l C {} +



      
